language: python
python:
        - 3.6
install:
        - pip install pylint
script:
        - pylint src/launch.py --disable=C0413,C0305
        - pylint src/menu.py --disable=C0413
        - pylint src/program.py --disable=R0902,C0413,C0305
        - pylint src/finish.py --disable=C0305
        - python -m unittest discover -s test -v
