language: python
python:
        - "3.6"
cache: pip
install:
        - pip install pylint
script:
        - pylint startprogram/launch.py
	- pylint menuprogram/menu.py
	- pylint mainprogram/program.py --disable=R0902
	- pylint end/finish.py 